"""Markdown report writer for szl-iso42001.

The report is the human-facing artifact; the receipt is the machine-facing one.
Two hard rules govern this module:

1. DETERMINISM. The report body contains no timestamp and no machine-specific
   data. Given the same ScoreResult, the bytes are identical on any machine,
   forever — that is what makes the receipt's sha256 meaningful.
2. HONESTY. The DISCLAIMER appears verbatim near the top of every report, the
   band is rendered exactly as computed, and the words "certified"/"compliant"
   are never used as verdicts. The footer tells the reader to verify this
   report against its receipt — every report points at its own provenance.
"""

from __future__ import annotations

from .controls import DISCLAIMER
from .score import BAND_NOT_READY, BAND_PARTIAL, BAND_READY, ScoreResult

REPORT_TITLE = "ISO/IEC 42001 + EU AI Act Art. 50 Readiness Report"
REPORT_FOOTER = "Generated by szl-iso42001 — verify this report against its receipt."

# Plain-language meaning of each band. Written for founders and auditors alike,
# and deliberately free of the words "certified"/"compliant".
_BAND_EXPLANATIONS = {
    BAND_READY: (
        "Weighted readiness is at or above 85% with no unresolved `no` on any "
        "weight-3 control. This suggests you are prepared to invite an "
        "accredited certification body to run a Stage-1 (documentation) audit. "
        "Only that body can certify you; this tool never will."
    ),
    BAND_PARTIAL: (
        "Material gaps remain. Either the weighted score is between 50% and "
        "85%, or a weight-3 control was answered `no` (which caps the band "
        "here regardless of score). Close the gaps below before booking an "
        "audit."
    ),
    BAND_NOT_READY: (
        "Foundational elements of an AI management system are missing or "
        "unproven. The prioritized gap list below is the work plan."
    ),
}

# Human-readable action labels for the two gap kinds.
_GAP_ACTION = {
    "NO_FIX": "Fix",
    "EVIDENCE_GAP": "Investigate",
}


def _fmt_pct(value: float) -> str:
    """Consistent one-decimal percentage formatting (e.g. 85.0 -> '85.0%')."""
    return f"{value:.1f}%"


def render_report(result: ScoreResult) -> str:
    """Render a full markdown readiness report from a ScoreResult.

    Pure function: same result in, same markdown out. Sections, in order:
    title, disclaimer, verdict, answer distribution, per-domain table,
    prioritized gap list, footer.
    """
    lines: list[str] = []

    # --- Title + disclaimer (the disclaimer is never optional) -------------
    lines.append(f"# {REPORT_TITLE}")
    lines.append("")
    lines.append(f"> **Disclaimer:** {DISCLAIMER}")
    lines.append("")

    # --- Verdict ------------------------------------------------------------
    lines.append("## Verdict")
    lines.append("")
    lines.append(f"**Band:** `{result.band}`")
    lines.append("")
    lines.append(
        f"**Overall weighted readiness:** {_fmt_pct(result.percentage)} "
        f"({result.earned:g} of {result.possible:g} weighted points)"
    )
    lines.append("")
    lines.append(_BAND_EXPLANATIONS[result.band])
    lines.append("")

    # --- Answer distribution -------------------------------------------------
    # 'unknown' is printed next to 'no' on purpose: both score zero, and the
    # reader should feel the full weight of what is unproven.
    lines.append("## Answer Distribution")
    lines.append("")
    lines.append("| Answer | Controls | Points earned per weight |")
    lines.append("|---|---|---|")
    lines.append(f"| yes | {result.counts['yes']} | 100% |")
    lines.append(f"| partial | {result.counts['partial']} | 50% |")
    lines.append(f"| no | {result.counts['no']} | 0% — must be fixed |")
    lines.append(f"| unknown | {result.counts['unknown']} | 0% — evidence gap |")
    lines.append("")

    # --- Per-domain table ----------------------------------------------------
    lines.append("## Readiness by Domain")
    lines.append("")
    lines.append("| Domain | Instrument | Readiness | Weighted points | Controls |")
    lines.append("|---|---|---|---|---|")
    for d in result.domain_scores:
        lines.append(
            f"| {d.domain} | {d.instrument} | {_fmt_pct(d.percentage)} "
            f"| {d.earned:g}/{d.possible:g} | {d.control_count} |"
        )
    lines.append("")

    # --- Prioritized gap list -------------------------------------------------
    # Ordering comes from score.prioritize_gaps: weight-3 'no' first, then other
    # NO_FIX, then EVIDENCE_GAPs. A green (gap-free) run still gets an explicit
    # section stating there is nothing left to close.
    lines.append("## Prioritized Gaps")
    lines.append("")
    if not result.gaps:
        lines.append(
            "No open gaps. Every control was answered `yes` or `partial`. "
            "Note: `partial` answers still earn only half credit — full "
            "readiness work continues."
        )
        lines.append("")
    else:
        lines.append(
            f"{len(result.gaps)} open item(s): "
            f"{len(result.no_fix_gaps)} to fix, "
            f"{len(result.evidence_gaps)} to investigate. "
            "Weight-3 items can block a Stage-1 audit on their own."
        )
        lines.append("")
        for rank, gap in enumerate(result.gaps, start=1):
            action = _GAP_ACTION[gap.kind]
            lines.append(
                f"{rank}. **[{action}] {gap.control_id} — {gap.title}** "
                f"(weight {gap.weight}, {gap.domain})"
            )
            lines.append(f"   - Evidence to gather: {gap.evidence_hint}")
        lines.append("")

    # --- Footer ---------------------------------------------------------------
    lines.append("---")
    lines.append("")
    lines.append(f"*{REPORT_FOOTER}*")
    lines.append("")

    return "\n".join(lines)
