"""The Covenant Proof Standard service — FastAPI surface.

Routes:

    GET /healthz
    GET /api/cps/claims
    GET /api/cps/claims/{claim_id}
    GET /api/cps/claims/{claim_id}/receipt
    GET /api/cps/report.md

Every number served is quoted verbatim from the claims file the store
loaded. This process performs NO recomputation of claim values — that is
szl-estate's job, across a file boundary. What this service does compute:
receipt identities (sha256 over claim bytes) and response timestamps, both
of which describe the serving event, never the claim's substance.

CORS is open and read-only: GET, HEAD, OPTIONS. Anyone's diligence tooling
may fetch these numbers; no one may push new ones through this API.
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import PlainTextResponse

from szl_claims_api.receipts import ReceiptMinter
from szl_claims_api.store import (
    BLOCKERS_HEADER,
    ClaimStore,
    default_claims_file_path,
)

__all__ = ["create_app"]


def _utcnow_iso() -> str:
    return datetime.now(UTC).isoformat().replace("+00:00", "Z")


def _public_claim(claim: dict[str, Any], receipt_id: str) -> dict[str, Any]:
    """The wire shape: claimed/actual verbatim from the file, plus receipt."""
    return {
        "claim_id": claim["claim_id"],
        "claimed": claim["expected"],
        "actual": claim["observed"],
        "last_run": claim["last_run"],
        "verdict": claim["verdict"],
        "drift": claim["verdict"] == "DRIFT",
        "receipt_id": receipt_id,
        "receipt_url": f"/api/cps/claims/{claim['claim_id']}/receipt",
    }


def _render_report(store: ClaimStore, minter: ReceiptMinter) -> str:
    """report.md — when any verdict is DRIFT, the line directly under the title
    is exactly BLOCKERS_HEADER and the drifting claims are listed first;
    otherwise the claims table follows the title. Store state, totals, and an
    honest server_time note form the footer (nothing may sit between the title
    and what matters most)."""
    claims = store.get_all()
    stats = store.stats()
    drifts = [c for c in claims if c["verdict"] == "DRIFT"]
    lines = ["# SZL Holdings — public claims, held to the Covenant Proof Standard"]
    if drifts:
        lines += [BLOCKERS_HEADER, ""]
        for claim in drifts:
            lines.append(
                f"- **HIGH** `CLAIM_DRIFT` — `{claim['claim_id']}`: claimed "
                f"{claim['expected']!r}, observed {claim['observed']!r} "
                f"(run {claim['last_run']}). {claim['evidence']}"
            )
        lines.append("")
    lines += [
        "| Claim | Claimed | Actual | Last run | Verdict | Drift | Receipt |",
        "|---|---|---|---|---|---|---|",
    ]
    for claim in claims:
        receipt_id = minter.receipt_for(claim)["receipt_id"]
        actual = claim["observed"] if claim["observed"] is not None else "—"
        last_run = claim["last_run"] if claim["last_run"] is not None else "—"
        drift = "YES" if claim["verdict"] == "DRIFT" else "no"
        escaped_claimed = str(claim["expected"]).replace("|", "\\|")
        lines.append(
            f"| {claim['claim_id']} | {escaped_claimed} | {actual} | {last_run} "
            f"| {claim['verdict']} | {drift} | `{receipt_id[:16]}…` |"
        )
    lines += [
        "",
        f"Store state: **{store.state}**" + (f" — {store.note}" if store.note else ""),
        "",
        f"Totals: {stats.total} claims — {stats.passed} PASS, {stats.drift} DRIFT, "
        f"{stats.unknown} UNKNOWN. UNKNOWN is never passing.",
        "",
        "_server_time note: generated by szl-claims-api at "
        f"{_utcnow_iso()}; every number above is quoted verbatim from the claims "
        "file written by an independent recomputation run (szl-estate). This service "
        "computes no claim values itself — it reports recomputations and receipts "
        "them; it does not invent them._",
        "",
    ]
    return "\n".join(lines)


def create_app(store_path: str | Path | None = None) -> FastAPI:
    """Build the service around a claims file. App factory for tests and serve."""
    store = ClaimStore(Path(store_path) if store_path is not None else default_claims_file_path())
    minter = ReceiptMinter()

    app = FastAPI(
        title="szl-claims-api",
        version="0.1.0",
        description=(
            "The live Covenant Proof Standard service: every public numeric claim "
            "SZL Holdings makes, receipted and recomputable."
        ),
    )
    app.add_middleware(
        CORSMiddleware,
        allow_origins=["*"],
        allow_methods=["GET"],
        allow_headers=["*"],
    )

    @app.get("/healthz")
    def healthz() -> dict[str, Any]:
        return {"status": "ok", "store_state": store.state, "server_time": _utcnow_iso()}

    @app.get("/api/cps/claims")
    def list_claims() -> dict[str, Any]:
        claims = store.get_all()
        return {
            "generated_at": _utcnow_iso(),
            "store_state": store.state,
            "note": store.note,
            "stats": store.stats().to_dict(),
            "claims": [
                _public_claim(claim, minter.receipt_for(claim)["receipt_id"])
                for claim in claims
            ],
        }

    @app.get("/api/cps/claims/{claim_id}")
    def get_claim(claim_id: str) -> dict[str, Any]:
        claim = store.get_one(claim_id)
        if claim is None:
            raise HTTPException(status_code=404, detail=f"unknown claim_id: {claim_id!r}")
        body = _public_claim(claim, minter.receipt_for(claim)["receipt_id"])
        body["description"] = claim["description"]
        body["source"] = claim["source"]
        body["evidence"] = claim["evidence"]
        body["store_state"] = store.state
        return body

    @app.get("/api/cps/claims/{claim_id}/receipt")
    def get_claim_receipt(claim_id: str) -> dict[str, Any]:
        claim = store.get_one(claim_id)
        if claim is None:
            raise HTTPException(status_code=404, detail=f"unknown claim_id: {claim_id!r}")
        return minter.receipt_for(claim)

    @app.get("/api/cps/report.md", response_class=PlainTextResponse)
    def report_md() -> PlainTextResponse:
        return PlainTextResponse(_render_report(store, minter), media_type="text/markdown")

    return app
