"""Report rendering tests.

The report is the human artifact a founder hands to a board or an auditor.
These tests pin: the mandated title, the verbatim disclaimer, the exact band,
the domain table, the prioritized gap section, and the receipt footer — plus
the determinism property that makes receipts meaningful.
"""

from __future__ import annotations

from szl_iso42001.controls import DISCLAIMER, load_controls
from szl_iso42001.report import REPORT_FOOTER, REPORT_TITLE, render_report
from szl_iso42001.score import BAND_NOT_READY, BAND_READY, score_answers


def full_corpus_result(answers: dict[str, object]):
    return score_answers(answers, load_controls())


def test_report_has_mandated_title_and_disclaimer():
    result = full_corpus_result({})
    md = render_report(result)
    assert f"# {REPORT_TITLE}" in md
    assert REPORT_TITLE == "ISO/IEC 42001 + EU AI Act Art. 50 Readiness Report"
    assert DISCLAIMER in md


def test_report_shows_band_and_percentage():
    controls = load_controls()
    result = score_answers({c.id: "yes" for c in controls}, controls)
    md = render_report(result)
    assert f"**Band:** `{BAND_READY}`" in md
    assert "100.0%" in md


def test_report_all_unknown_is_honest_not_ready():
    md = render_report(full_corpus_result({}))
    assert f"**Band:** `{BAND_NOT_READY}`" in md
    assert "0.0%" in md
    # Every control must appear as an investigation item — never silently dropped.
    for c in load_controls():
        assert c.id in md


def test_report_domain_table_lists_every_domain():
    md = render_report(full_corpus_result({}))
    for c in load_controls():
        assert f"| {c.domain} |" in md
    assert "| Domain | Instrument | Readiness | Weighted points | Controls |" in md


def test_report_prioritizes_weight3_no_first_then_evidence_gaps():
    controls = load_controls()
    weight3 = next(c for c in controls if c.weight == 3)
    # One weight-3 'no', everything else unknown.
    answers = {weight3.id: "no"}
    md = render_report(full_corpus_result(answers))
    gap_section = md.split("## Prioritized Gaps", 1)[1]
    first_item_line = next(
        line for line in gap_section.splitlines() if line.startswith("1. ")
    )
    assert weight3.id in first_item_line
    assert "[Fix]" in first_item_line  # NO_FIX renders as a Fix action


def test_report_footer_points_at_receipt():
    md = render_report(full_corpus_result({}))
    assert REPORT_FOOTER in md
    assert REPORT_FOOTER == (
        "Generated by szl-iso42001 — verify this report against its receipt."
    )


def test_report_is_deterministic():
    controls = load_controls()
    answers = {controls[0].id: "yes", controls[1].id: "partial"}
    first = render_report(score_answers(answers, controls))
    second = render_report(score_answers(answers, controls))
    assert first == second


def test_report_never_uses_certified_or_compliant_as_verdict():
    # The verdict line may explain what an accredited body does, but the band
    # token itself must be one of the three honest bands.
    md = render_report(full_corpus_result({}))
    verdict = md.split("## Verdict", 1)[1].split("##", 1)[0]
    band_line = next(line for line in verdict.splitlines() if "**Band:**" in line)
    assert any(b in band_line for b in
               ("NOT_READY", "PARTIAL", "READY_FOR_STAGE1_AUDIT"))


def test_report_gap_free_run_says_so():
    controls = load_controls()
    answers = {c.id: "yes" for c in controls}
    md = render_report(score_answers(answers, controls))
    assert "No open gaps." in md
